In [1]:
import pandas as pd
import networkx as nx

In [2]:
종로 = pd.read_csv('종로구_pm보간데이터.csv', index_col = 0)

### 종로구 pagerank

In [3]:
###pagerank pm10
td_list = []
for idx in 종로['동'].unique():
    td_list.append(idx)
td_list.append('date')
colm = pd.DataFrame(columns = td_list)
G = nx.DiGraph()
for idx,val in enumerate(종로['date_daily'].unique()):
    b = 종로[종로['date_daily']==val].sort_values('pm10', ascending = False).reset_index(drop=True)
    if b['pm10'][1] > 31:
        G.add_edge(b['동'][1], b['동'][0], weight = float(b['pm10'][0])-float(b['pm10'][1]))
    if b['pm10'][2] > 31:
        G.add_edge(b['동'][2], b['동'][0], weight = float(b['pm10'][0])-float(b['pm10'][2]))
        G.add_edge(b['동'][2], b['동'][1], weight = float(b['pm10'][1])-float(b['pm10'][2]))
    if b['pm10'][3] > 31:
        G.add_edge(b['동'][3], b['동'][0], weight = float(b['pm10'][0])-float(b['pm10'][3]))
        G.add_edge(b['동'][3], b['동'][1], weight = float(b['pm10'][1])-float(b['pm10'][3]))
        G.add_edge(b['동'][3], b['동'][2], weight = float(b['pm10'][2])-float(b['pm10'][3]))
    if b['pm10'][4] > 31:
        G.add_edge(b['동'][4], b['동'][0], weight = float(b['pm10'][0])-float(b['pm10'][4]))
        G.add_edge(b['동'][4], b['동'][1], weight = float(b['pm10'][1])-float(b['pm10'][4]))
        G.add_edge(b['동'][4], b['동'][2], weight = float(b['pm10'][2])-float(b['pm10'][4]))
        G.add_edge(b['동'][4], b['동'][3], weight = float(b['pm10'][3])-float(b['pm10'][4]))

pr=nx.pagerank(G)
colm = pd.DataFrame([pr])
ted = colm.T
ted.columns = ['year_pm10_ranking']
종로구 = ted.sort_values('year_pm10_ranking', ascending = False)

In [4]:
###pagerank pm25
td_list = []
for idx in 종로['동'].unique():
    td_list.append(idx)
td_list.append('date')
colm = pd.DataFrame(columns = td_list)
G = nx.DiGraph()
for idx,val in enumerate(종로['date_daily'].unique()):
    b = 종로[종로['date_daily']==val].sort_values('pm25', ascending = False).reset_index(drop=True)
    if b['pm25'][1] > 31:
        G.add_edge(b['동'][1], b['동'][0], weight = float(b['pm25'][0])-float(b['pm25'][1]))
    if b['pm25'][2] > 31:
        G.add_edge(b['동'][2], b['동'][0], weight = float(b['pm25'][0])-float(b['pm25'][2]))
        G.add_edge(b['동'][2], b['동'][1], weight = float(b['pm25'][1])-float(b['pm25'][2]))
    if b['pm25'][3] > 31:
        G.add_edge(b['동'][3], b['동'][0], weight = float(b['pm25'][0])-float(b['pm25'][3]))
        G.add_edge(b['동'][3], b['동'][1], weight = float(b['pm25'][1])-float(b['pm25'][3]))
        G.add_edge(b['동'][3], b['동'][2], weight = float(b['pm25'][2])-float(b['pm25'][3]))
    if b['pm25'][4] > 31:
        G.add_edge(b['동'][4], b['동'][0], weight = float(b['pm25'][0])-float(b['pm25'][4]))
        G.add_edge(b['동'][4], b['동'][1], weight = float(b['pm25'][1])-float(b['pm25'][4]))
        G.add_edge(b['동'][4], b['동'][2], weight = float(b['pm25'][2])-float(b['pm25'][4]))
        G.add_edge(b['동'][4], b['동'][3], weight = float(b['pm25'][3])-float(b['pm25'][4]))
pr=nx.pagerank(G)
colm = pd.DataFrame([pr])

In [5]:
ted = colm.T
ted.columns = ['year_pm25_ranking']

In [6]:
종로구 = 종로구.join(ted.sort_values('year_pm25_ranking', ascending = False))

In [7]:
종로구.to_csv('종로구_pagerank.csv')

In [8]:
종로구

              year_pm10_ranking  year_pm25_ranking
평창동                    0.145005           0.106280
청운효자동                  0.087154           0.093447
교남동                    0.080005           0.077974
가회동                    0.079365           0.070509
숭인2동                   0.073868           0.061929
숭인1동                   0.064015           0.058650
혜화동                    0.063765           0.044737
부암동                    0.062198           0.129466
창신3동                   0.061337           0.056621
삼청동                    0.052266           0.050920
이화동                    0.047379           0.045088
창신1동                   0.046013           0.050271
사직동                    0.042287           0.040663
종로5,6가동                0.031035           0.035605
종로 1,2,3,4가동           0.030103           0.035732
무악동                    0.020665           0.021635
창신2동                   0.013541           0.020473

# 노원구 pagerank

In [9]:
노원 = pd.read_csv('노원구_pm보간데이터.csv', index_col = 0)

In [14]:
###pagerank pm10
td_list = []
for idx in 노원['동'].unique():
    td_list.append(idx)
td_list.append('date')
colm = pd.DataFrame(columns = td_list)
G = nx.DiGraph()
for idx,val in enumerate(노원['date_daily'].unique()):
    b = 노원[노원['date_daily']==val].sort_values('pm10', ascending = False).reset_index(drop=True)
    if b['pm10'][1] > 31:
        G.add_edge(b['동'][1], b['동'][0], weight = float(b['pm10'][0])-float(b['pm10'][1]))
    if b['pm10'][2] > 31:
        G.add_edge(b['동'][2], b['동'][0], weight = float(b['pm10'][0])-float(b['pm10'][2]))
        G.add_edge(b['동'][2], b['동'][1], weight = float(b['pm10'][1])-float(b['pm10'][2]))
    if b['pm10'][3] > 31:
        G.add_edge(b['동'][3], b['동'][0], weight = float(b['pm10'][0])-float(b['pm10'][3]))
        G.add_edge(b['동'][3], b['동'][1], weight = float(b['pm10'][1])-float(b['pm10'][3]))
        G.add_edge(b['동'][3], b['동'][2], weight = float(b['pm10'][2])-float(b['pm10'][3]))
    if b['pm10'][4] > 31:
        G.add_edge(b['동'][4], b['동'][0], weight = float(b['pm10'][0])-float(b['pm10'][4]))
        G.add_edge(b['동'][4], b['동'][1], weight = float(b['pm10'][1])-float(b['pm10'][4]))
        G.add_edge(b['동'][4], b['동'][2], weight = float(b['pm10'][2])-float(b['pm10'][4]))
        G.add_edge(b['동'][4], b['동'][3], weight = float(b['pm10'][3])-float(b['pm10'][4]))

pr=nx.pagerank(G)
colm = pd.DataFrame([pr])
ted = colm.T
ted.columns = ['year_pm10_ranking']
노원구 = ted.sort_values('year_pm10_ranking', ascending = False)

In [15]:
###pagerank pm25
td_list = []
for idx in 노원['동'].unique():
    td_list.append(idx)
td_list.append('date')
colm = pd.DataFrame(columns = td_list)
G = nx.DiGraph()
for idx,val in enumerate(노원['date_daily'].unique()):
    b = 노원[노원['date_daily']==val].sort_values('pm25', ascending = False).reset_index(drop=True)
    if b['pm25'][1] > 31:
        G.add_edge(b['동'][1], b['동'][0], weight = float(b['pm25'][0])-float(b['pm25'][1]))
    if b['pm25'][2] > 31:
        G.add_edge(b['동'][2], b['동'][0], weight = float(b['pm25'][0])-float(b['pm25'][2]))
        G.add_edge(b['동'][2], b['동'][1], weight = float(b['pm25'][1])-float(b['pm25'][2]))
    if b['pm25'][3] > 31:
        G.add_edge(b['동'][3], b['동'][0], weight = float(b['pm25'][0])-float(b['pm25'][3]))
        G.add_edge(b['동'][3], b['동'][1], weight = float(b['pm25'][1])-float(b['pm25'][3]))
        G.add_edge(b['동'][3], b['동'][2], weight = float(b['pm25'][2])-float(b['pm25'][3]))
    if b['pm25'][4] > 31:
        G.add_edge(b['동'][4], b['동'][0], weight = float(b['pm25'][0])-float(b['pm25'][4]))
        G.add_edge(b['동'][4], b['동'][1], weight = float(b['pm25'][1])-float(b['pm25'][4]))
        G.add_edge(b['동'][4], b['동'][2], weight = float(b['pm25'][2])-float(b['pm25'][4]))
        G.add_edge(b['동'][4], b['동'][3], weight = float(b['pm25'][3])-float(b['pm25'][4]))
pr=nx.pagerank(G)
colm = pd.DataFrame([pr])

In [16]:
ted = colm.T
ted.columns = ['year_pm25_ranking']
노원구 = 노원구.join(ted.sort_values('year_pm25_ranking', ascending = False))
노원구.to_csv('노원구_pagerank.csv')

In [17]:
노원구

        year_pm10_ranking  year_pm25_ranking
상계5동             0.097237           0.078048
상계9동             0.096882           0.097873
상계1동             0.092155           0.085718
월계3동             0.091047           0.125326
상계10동            0.085044           0.112979
상계2동             0.050949           0.038014
중계본동             0.049861           0.067931
중계2,3동           0.045794           0.045042
중계1동             0.044643           0.038968
중계4동             0.044528           0.046998
월계1동             0.044081           0.032630
상계6,7동           0.042545           0.038914
상계8동             0.040643           0.049614
공릉2동             0.039016           0.025685
월계2동             0.038625           0.021755
상계3,4동           0.037452           0.033237
하계1동             0.026124           0.013028
공릉1동             0.017446           0.026295
하계2동             0.015928           0.021943